user www-data;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
error_log /proc/1/fd/1 notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for" '
    '"$remote_addr" "$http_host"';
    access_log /var/log/nginx/access.log main buffer=16k flush=2m;

    include mime.types;
    default_type application/octet-stream;

    server_tokens off;
    charset utf-8;
    http2 on;
    resolver 127.0.0.11;
    gzip on;

    ssl_protocols TLSv1.3;

    include conf.d/*.conf;

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;

        return 308 https://$host$request_uri;
    }

    server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        listen 443 quic default_server;
        listen [::]:443 quic default_server;
        server_name _;

        ssl_reject_handshake on;
    }
}
