services:
  nginx:
    image: nginx:1.30-trixie@sha256:5825bde471b86b270298e80ba1f0f3e515a73da1a17a982632f1c262689f1144
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro

      - ./nginx/html:/usr/share/nginx/html:ro
      - ./certs/nginx:/cert:ro
      - ./nginx/log:/var/log/nginx:rw
    environment:
      TZ: Pacific/Auckland
    restart: always

  api:
    image: ghcr.io/bozhanl/rehua-api:main@sha256:9d6094d1356733a3fc4fe42865916ca5e110bde64445b2f23ff354b0f6d285a1
    environment:
      TZ: Pacific/Auckland

      NODE_ENV: production

      API_CERT: /cert/api.pem
      API_KEY: /cert/api.key
      API_CA: /cert/ca.pem
      MONGODB_URI_FILE: /run/secrets/mongo_url
    volumes:
      - ./certs/api:/cert:ro
    secrets:
      - mongo_url
    init: true
    restart: always

  mongo:
    image: mongo:8.3@sha256:0f887198e29c093fd2b36c3e2eb43c7b98e47c081d89fbd5bc212da0cd43ec58
    restart: unless-stopped
    environment:
      TZ: Pacific/Auckland
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    user: 1000:1000
    volumes:
      - ./mongo/data:/data/db:rw
      - ./mongo/configdb:/data/configdb:rw

      - ./mongo/config:/etc/mongo:ro
      - ./certs/mongo:/cert:ro

      - ./mongo/log:/var/log/mongodb:rw
    secrets:
      - mongo_username
      - mongo_password
    command: ['--config', '/etc/mongo/mongod.conf']

secrets:
  mongo_url:
    file: ./mongo/mongodb_url.txt

  mongo_username:
    file: ./mongo/mongo_username.txt
  mongo_password:
    file: ./mongo/mongo_password.txt
