services:
    nginx:
        image: nginx:1.30-trixie@sha256:46ccc48fbb1f5a43167f2ee2c279c122b96eec5d976e7f4e1e0780f59a51b4d6
        ports:
            - 80:80/tcp
            - 443:443/tcp
            - 443:443/udp
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro

            - ./nginx/html:/usr/share/nginx/html:ro
            - ./certs/nginx:/cert:ro
            - ./nginx/log:/var/log/nginx:rw
        environment:
            TZ: Pacific/Auckland
        restart: always

    api:
        image: ghcr.io/bozhanl/rehua-api:main
        environment:
            TZ: Pacific/Auckland

            NODE_ENV: production

            API_CERT: /cert/api.pem
            API_KEY: /cert/api.key
            API_CA: /cert/ca.pem
            MONGODB_URI_FILE: /run/secrets/mongo_url
        volumes:
            - ./certs/api:/cert:ro
        secrets:
            - mongo_url
        init: true
        restart: always

    mongo:
        image: mongo:8.3@sha256:2f02e2184c6d91c3208e5ab75a0707d1386a05377b20fdaf49a314815774d863
        restart: unless-stopped
        environment:
            TZ: Pacific/Auckland
            MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
            # Work around MongoDB 8.0+ startup crashes on Linux kernel 6.19
            # https://jira.mongodb.org/browse/SERVER-121912?focusedId=8395283
            GLIBC_TUNABLES: glibc.pthread.rseq=1
        user: 1000:1000
        volumes:
            - ./mongo/data:/data/db:rw
            - ./mongo/configdb:/data/configdb:rw

            - ./mongo/config:/etc/mongo:ro
            - ./certs/mongo:/cert:ro

            - ./mongo/log:/var/log/mongodb:rw
        secrets:
            - mongo_username
            - mongo_password
        command: ['--config', '/etc/mongo/mongod.conf']

secrets:
    mongo_url:
        file: ./mongo/mongodb_url.txt

    mongo_username:
        file: ./mongo/mongo_username.txt
    mongo_password:
        file: ./mongo/mongo_password.txt
