services:
    app:
        image: mcr.microsoft.com/devcontainers/python:3.14-trixie@sha256:f04a1e9c29e371436d6086908eed22ac0ba087bae0f8edb826838283cf3d1726
        volumes:
            - ../..:/workspaces:cached
        command: sleep infinity
