services:
    app:
        image: mcr.microsoft.com/devcontainers/python:3.14-trixie@sha256:1c3a6304ca90d6843915738d1adfbc4db1a660a65fa96948b88048357cc3811a
        volumes:
            - ../..:/workspaces:cached
        command: sleep infinity
