services:
    app:
        image: mcr.microsoft.com/devcontainers/python:3.14-trixie@sha256:824bd18367c4c8c79f21f195f26f59733d303ceecc77c1a10f301ef315f96b1f
        volumes:
            - ../..:/workspaces:cached
        command: sleep infinity
