upstream api {
    server api:3001 resolve;
    zone api 32k;
}

server {
    listen 80;
    listen [::]:80;
    server_name localhost;
    return 302 https://localhost$request_uri;
}

map $server_protocol $altSvc {
    default 'h3=":$server_port"; ma=86400, h2=":$server_port"; ma=86400';
    'HTTP/2.0' 'h3=":$server_port"; ma=86400';
    'HTTP/3.0' '';
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;

    server_name localhost;

    ssl_certificate /cert/fullchain.pem;
    ssl_certificate_key /cert/localhost.key;

    add_header Alt-Svc $altSvc always;

    root /usr/share/nginx/html/rehua/;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location /api/ {
        proxy_pass https://api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_ssl_protocols TLSv1.3;
        proxy_ssl_server_name on;

        proxy_ssl_verify on;
        proxy_ssl_trusted_certificate /cert/ca.pem;
        proxy_ssl_verify_depth 3;

        proxy_ssl_certificate /cert/localhost.pem;
        proxy_ssl_certificate_key /cert/localhost.key;

        # allow upload large file
        client_max_body_size 100M;
    }
}
